export default {
  banner: require('./banner.png'),
  flash1: require('./flash1.png'),
  flash2: require('./flash2.png'),
  flash3: require('./flash3.png'),
  home1: require('./home1.png'),
  home2: require('./home2.png'),
  home3: require('./home3.png'),
  home4: require('./home4.png'),
  mega1: require('./mega1.png'),
  mega2: require('./mega2.png'),
  mega3: require('./mega3.png'),
  profile: require('./profile.png'),
  recommend: require('./recommend.png'),
  shoes1: require('./shoes1.png'),
  shoes2: require('./shoes2.png'),
  shoes3: require('./shoes3.png'),
};
